/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define DEFAULT_LOCAL_PORT_RANGE_FIRST 27183

#define DEFAULT_LOCAL_PORT_RANGE_LAST 27199

#define HAVE_ASPRINTF

#define HAVE_JRAND48

#define HAVE_NRAND48

#undef HAVE_SOCK_CLOEXEC

#define HAVE_STRDUP

#define HAVE_USB

#undef HAVE_V4L2

#define HAVE_VASPRINTF

#define PORTABLE

#define PREFIX "/opt/homebrew"

#define SCRCPY_VERSION "3.3.4"

#undef SERVER_DEBUGGER

#define _DARWIN_C_SOURCE

#define _GNU_SOURCE

#define _POSIX_C_SOURCE 200809L

#define _XOPEN_SOURCE 700

